// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGfUmS5-9iCQNdaP9AVm3Pmia6nQIX1uc',
    appId: '1:752130023664:android:d2fb6cd4246f0b99152235',
    messagingSenderId: '752130023664',
    projectId: 'ayurlive-dashboard-b4e15',
    storageBucket: 'ayurlive-dashboard-b4e15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmmzdgSJv1Zle5fJ9mo2w8s7wnTW8gups',
    appId: '1:752130023664:ios:3e387734d9d87ad7152235',
    messagingSenderId: '752130023664',
    projectId: 'ayurlive-dashboard-b4e15',
    storageBucket: 'ayurlive-dashboard-b4e15.firebasestorage.app',
    iosBundleId: 'com.touchq.ayurlivedashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmmzdgSJv1Zle5fJ9mo2w8s7wnTW8gups',
    appId: '1:752130023664:ios:3e387734d9d87ad7152235',
    messagingSenderId: '752130023664',
    projectId: 'ayurlive-dashboard-b4e15',
    storageBucket: 'ayurlive-dashboard-b4e15.firebasestorage.app',
    iosBundleId: 'com.touchq.ayurlivedashboard',
  );
}
