import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import 'core/constants/string_constants.dart';
import 'core/di/injector.dart';
import 'core/di/local_storage_service.dart';
import 'core/services/notification_center_service.dart';
import 'core/utils/app_logger.dart';
import 'presentation/blocs/auth/auth_bloc.dart';
import 'presentation/blocs/dashboard/dashboard_bloc.dart';
import 'presentation/screens/accounts/accounts_screen.dart';
import 'presentation/screens/banquet/banquet_screen.dart';
import 'presentation/screens/bar/bar_screen.dart';
import 'presentation/screens/base_url/base_url_screen.dart';
import 'presentation/screens/emr/emr_screen.dart';
import 'presentation/screens/frontoffice/frontoffice_screen.dart';
import 'presentation/screens/home/home_screen.dart';
import 'presentation/screens/hr/hr_screen.dart';
import 'presentation/screens/lab/lab_screen.dart';
import 'presentation/screens/login/login_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

import 'core/services/notification_service.dart';
import 'firebase_options.dart';
import 'presentation/screens/restaurant/restaurant_screen.dart';
import 'presentation/screens/store/store_screen.dart'; // generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase MUST be initialized before anything else uses it.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Register the background message handler.
  // Top-level function reference — see notification_service.dart.
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  // Initialize app dependencies (your existing setup).
  await setupDependencies();

  // Initialize unread badge service BEFORE NotificationService
  // so the badge count is loaded when notifications start arriving.
  await NotificationCenterService().init();

  // Initialize the notification service after Firebase is ready.
  await NotificationService.init();

  // OPTIONAL: subscribe to a broadcast topic so EVERY user receives
  // pushes the backend sends to 'all-users'.
  await NotificationService.subscribeToTopic('all-users');

  runApp(const AyurlivApp());
}

class AyurlivApp extends StatelessWidget {
  const AyurlivApp({super.key});

  @override
  Widget build(BuildContext context) {
    // AuthBloc is a singleton so it spans BaseUrl → Login → Branch.
    return BlocProvider<AuthBloc>(
      create: (_) => autoInjector.get<AuthBloc>(),
      child: MaterialApp(
        navigatorKey: NotificationService.navigatorKey,
        title: StringConstants.appName,
        debugShowCheckedModeBanner: false,
        // theme: AppTheme.light,
        home: const _RouteGate(),
        // Optional: named routes if you want tap-navigation to work.
        routes: {
          '/home': (_) => const HomeScreen(),
          '/emr': (_) => const EmrScreen(),
          '/accounts': (_) => const AccountsScreen(),
          '/store': (_) => const StoreScreen(),
          '/bar': (_) => const BarScreen(),
          '/lab': (_) => const LabScreen(),
          '/restaurant': (_) => const RestaurantScreen(),
          '/hr': (_) => const HrScreen(),
          '/banquet': (_) => const BanquetScreen(),
          '/frontoffice': (_) => const FrontofficeScreen(),
        },
      ),
    );
  }
}

/// Decides what to show on cold start based on persisted state:
///
///   1. No baseUrl saved              → BaseUrlScreen
///   2. baseUrl + no session          → LoginScreen
///   3. baseUrl + session + no branch → LoginScreen (re-pick branch)
///   4. Fully authenticated           → HomeScreen
///
/// Also fires AuthBootstrapped once on mount so AuthBloc rehydrates
/// persisted state (branch list) — this is why the drawer wasn't showing
/// branches on cold start before.
///
/// Notes:
///  • This runs ONLY on cold start. Once you're past this gate, normal
///    Navigator pushes/pops apply.
///  • "Remember me" prefilling is handled inside LoginScreen — even if
///    the session was cleared (logout / token expiry), the saved Account
///    ID + Username come back in the form for one-tap login.
class _RouteGate extends StatefulWidget {
  const _RouteGate();

  @override
  State<_RouteGate> createState() => _RouteGateState();
}

class _RouteGateState extends State<_RouteGate> {
  static const _tag = 'RouteGate';

  @override
  void initState() {
    super.initState();

    // Rehydrate persisted auth state (branch list) so the drawer isn't
    // empty when the user opens the app on Day 2 without re-logging in.
    // Runs once per app cold-start.
    //
    // Note: no-op if there are no persisted branches (e.g. very first
    // launch or after logout). AuthBloc just logs "no persisted branches"
    // and does nothing else.
    context.read<AuthBloc>().add(const AuthBootstrapped());
  }

  @override
  Widget build(BuildContext context) {
    final storage = autoInjector.get<LocalStorageService>();
    final baseUrl = storage.baseUrl;
    final hasSession = storage.hasSession;
    final branch = storage.selectedBranch;

    AppLogger.info(
      _tag,
      'baseUrl="${baseUrl ?? ''}" hasSession=$hasSession branch="${branch ?? ''}"',
    );

    if (baseUrl == null || baseUrl.isEmpty) {
      AppLogger.info(_tag, '→ BaseUrlScreen');
      return const BaseUrlScreen();
    }

    if (!hasSession) {
      AppLogger.info(_tag, '→ LoginScreen (no session)');
      return const LoginScreen();
    }

    if (branch == null || branch.isEmpty) {
      AppLogger.info(_tag, '→ LoginScreen (no branch)');
      return const LoginScreen();
    }

    AppLogger.info(_tag, '→ HomeScreen');
    return BlocProvider<DashboardBloc>(
      create: (_) => autoInjector.get<DashboardBloc>()
        ..add(const DashboardLoadRequested()),
      child: const HomeScreen(),
    );
  }
}
